version: "3"

services:
    everglot-lp:
        image: everglot/everglot-lp:latest
        build:
            context: .
        restart: always
        working_dir: /home/node/app
        ports:
            - "127.0.0.1:3000:3000"
