version: "3"

services:
    everglot-lp:
        entrypoint: "npm run dev"
        volumes:
            - ./:/home/node/app
        environment:
            PGUSER: everglot_lp_user
            PGPASSWORD: everglot_lp_pass
            PGDATABASE: everglot_lp_db
            PGHOST: db
            PGPORT: 5432
            NODE_ENV: "development"
            NODE_OPTIONS: "--max_old_space_size=8192"
            ROARR_LOG: "true"
            HOST: "0.0.0.0"
            PORT: "3000"
        ports:
            - "0.0.0.0:3000:3000"
            - "0.0.0.0:10000:10000"
    db:
        environment:
            POSTGRES_USER: "everglot_lp_user"
            POSTGRES_PASSWORD: "everglot_lp_pass"
            POSTGRES_DB: "everglot_lp_db"
