version: "3"

services:
    everglot-lp:
        image: everglot/everglot-lp:latest
        build:
            context: .
        restart: always
        working_dir: /home/node/app
        environment:
            PGUSER: ${POSTGRES_USER:?Please set POSTGRES_USER}
            PGPASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD}
            PGDATABASE: ${POSTGRES_DB:?Please set POSTGRES_DB}
            PGHOST: ${PGHOST:-db}
            PGPORT: ${PGPORT:-5432}
            DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PGHOST:-db}:${PGPORT}/${POSTGRES_DB}"
    db:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER:?Please set POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB:?Please set POSTGRES_DB}
