version: "3"

services:
    everglot-lp:
        entrypoint: "npm run dev"
        volumes:
            - ./:/home/node/app
        environment:
            PGUSER: everglot_lp_user
            PGPASSWORD: everglot_lp_pass
            PGDATABASE: everglot_lp_db
            PGHOST: db
            PGPORT: 5432
    db:
        environment:
            POSTGRES_USER: "everglot_lp_user"
            POSTGRES_PASSWORD: "everglot_lp_pass"
            POSTGRES_DB: "everglot_lp_db"
