version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest
            # - image: circleci/mongo:3.6-xenial
        steps:
            - checkout
            # - run:
            #     name: install dependencies
            #     command: npm install
            # - run:
            #     name: run tests
            #     command: npm test
    deploy:
        machine:
            enabled: true
        steps:
            - run:
                  name: Deploy Over SSH
                  command: |
                      ssh root@68.183.15.247 "cd ~/everglot/landingpage; git checkout -- .; git pull; docker build -t everglot/everglot-lp:latest .; docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d"

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: main
